apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 0
spec:
  serviceName: ${PROJECT_NAME}-service
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}-statefulset
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}-statefulset
    spec:
      serviceAccountName: operator-controller-manager
      containers:
        - name: cmd
          image: ${EPP_IMAGE}
          imagePullPolicy: Always
