kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${EPP_NAME}
rules:
- apiGroups:
  - "inference.networking.x-k8s.io"
  resources:
  - "inferencepools"
  - "inferenceobjectives"
  - "inferencemodelrewrites"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "inference.networking.k8s.io"
  resources:
  - "inferencepools"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - "tokenreviews"
  verbs:
  - "create"
- apiGroups:
  - "authorization.k8s.io"
  resources:
  - "subjectaccessreviews"
  verbs:
  - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${EPP_NAME}-binding
subjects:
- kind: ServiceAccount
  name: ${EPP_NAME}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${EPP_NAME}
