name: CI - Release - Docker Container Image

on:
  push:
    tags:
      - 'v*'  # Runs when a tag like v0.1.0 is pushed
  release:
    types: [published]  # Also runs when a GitHub release is published

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Checkout source
        uses: actions/checkout@v6

      - name: Set image names
        id: version
        run: |
          repo="${GITHUB_REPOSITORY##*/}"
          echo "project_name=$repo" >> "$GITHUB_OUTPUT"
          echo "sidecar_name=llm-d-routing-sidecar" >> "$GITHUB_OUTPUT"

      - name: Print project name
        run: echo "Project is ${{ steps.version.outputs.project_name }}"

      - name: Determine tag name
        id: tag
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            echo "tag=${GITHUB_REF##refs/tags/}" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF##refs/tags/}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          fi
          PRE_RELEASE=${{ github.event_name != 'release' || github.event.release.prerelease }}
          echo "prerelease=${PRE_RELEASE}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Build and push EPP image
        uses: ./.github/actions/docker-build-and-push
        with:
          docker-file: Dockerfile.epp
          tag: ${{ steps.tag.outputs.tag }}
          image-name: ${{ steps.version.outputs.project_name }}
          registry: ghcr.io/llm-d
          github-token: ${{ secrets.GHCR_TOKEN }}
          prerelease: ${{ steps.tag.outputs.prerelease }}

      - name: Build and push sidecar image
        uses: ./.github/actions/docker-build-and-push
        with:
          docker-file: Dockerfile.sidecar
          tag: ${{ steps.tag.outputs.tag }}
          image-name: ${{ steps.version.outputs.sidecar_name }}
          registry: ghcr.io/llm-d
          github-token: ${{ secrets.GHCR_TOKEN }}
          prerelease: ${{ steps.tag.outputs.prerelease }}

      - name: Run Trivy scan on EPP image
        uses: ./.github/actions/trivy-scan
        with:
          image: ghcr.io/llm-d/${{ steps.version.outputs.project_name }}:${{ steps.tag.outputs.tag }}

      - name: Run Trivy scan on sidecar image
        uses: ./.github/actions/trivy-scan
        with:
          image: ghcr.io/llm-d/${{ steps.version.outputs.sidecar_name }}:${{ steps.tag.outputs.tag }}
