name: Check Signed Commits in PR

on:
  pull_request_target:

jobs:
  check-signed-commits:
    name: Check signed commits in PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required to post comments on PRs
    steps:
      - name: Check signed commits in PR
        uses: 1Password/check-signed-commits-action@v1 # Use the action
        with:
          comment: |
            ðŸš¨ Unsigned commits detected! Please sign your commits.

            For instructions on how to set up GPG/SSH signing and verify your commits, please see [GitHub Documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification).
